#!/usr/bin/env python

# ch7/ex7
from sys import argv

from solutions.exercises.ch7.ex7.rotatable_linked_queue import RotatableLinkedQueue


def _main():
    n = int(argv[1]) if len(argv) > 1 else 10
    Q = RotatableLinkedQueue()
    for i in range(n):
        Q.enqueue(i)
    print("Q: {}".format(Q))
    for _ in range(n):
        print("Rotating Q ...")
        Q.rotate()
        print("Q: {}".format(Q))


if __name__ == "__main__":
    _main()
