#!/usr/bin/env python

# ch7/ex5
from sys import argv

from solutions.exercises.ch7.ex5.circular_linked_list import CircularLinkedList

def _main():
    # Create a circular linked list
    cll = CircularLinkedList()

    for i in range(int(argv[1]) if len(argv) > 1 else 10):
        cll.append(i)
    
    # Count the nodes
    print("Number of nodes:", cll.count_nodes())


if __name__ == "__main__":
    _main()
